Work around server-side issues with Accept-Language header handling
wikimedia/wikipedia-ios pull request #3699
Opened 2020-09-17 15:27 UTC by joewalsh

Sets a single Wikipedia-specific language code to the `Accept-Language` header for zhwiki and srwiki. This works around server-side issues handling standard `Accept-Language` headers as documented in [T256491](https://phabricator.wikimedia.org/T256491). The `Accept-Language` header workaround can be removed when [T256491](https://phabricator.wikimedia.org/T256491) is fixed.

**Fixes Phabricator ticket:** 
https://phabricator.wikimedia.org/T254627

### Test Steps
Utilize repro steps from https://phabricator.wikimedia.org/T254627

### Screenshots

No preference:
![No pref](https://user-images.githubusercontent.com/741327/93492311-a8646e80-f8d8-11ea-90f3-5bfe9aa434a3.png)

Traditional:
![Traditional](https://user-images.githubusercontent.com/741327/93492331-ac908c00-f8d8-11ea-9672-ba13100b7f55.png)

Simplified:
![Simplified](https://user-images.githubusercontent.com/741327/93492345-b0bca980-f8d8-11ea-8ef3-eb2aee445415.png)

2020-09-17 15:30 UTC, joewalsh commented
Hold pending triage into 6.7.1 or later

2020-09-17 20:52 UTC, joewalsh commented on Wikipedia/Code/ArticleFetcher.swift
> +    }
Heads up that this isn't completely new code - it was brought in from the summary fetcher

2020-09-18 20:47 UTC, tonisevener requested changes

2020-09-18 20:47 UTC, tonisevener commented on Wikipedia/Code/ArticleFetcher.swift
> +        var requestHeaders = configuration.pageContentServiceHeaders(for: url.wmf_language)
Only thing I've noticed is I think the Edit Preview endpoints need these `Accept-Language` values set as well. It doesn't look like they build their `URLRequest`s by leaning on this method.

2020-09-21 22:38 UTC, tonisevener commented
I noticed this wasn't working in the Staging environment - it wasn't properly pulling `wmf_language` for that url form. I attempted to fix in [this commit](https://github.com/wikimedia/wikipedia-ios/commit/b91d1e0f61c339719c5831cfd15aff260994b53d). Feel free to pull it in if you'd like, it felt a bit messy though so I didn't want to commit directly.

2020-09-22 22:55 UTC, tonisevener approved these changes

2020-09-22 22:56 UTC, merged