Add subscription methods to TalkPageFetcher
wikimedia/wikipedia-ios pull request #4273
Opened 2022-07-11 12:48 UTC by mazevedofs

**Phabricator:** https://phabricator.wikimedia.org/T311071 

### Notes
* This PR adds methods for subscribing/unsubscribing to topics and getting all the topics currently subscribed

### Test Steps
1. Run the app on staging
2. Add a call to the methods to our new [TalkPageViewController](https://github.com/wikimedia/wikipedia-ios/blob/4b927a509a147ec02ae323bf728746620a818089/Wikipedia/Code/TalkPageViewController.swift#L31)
3. Run and check on the web if it was successful (subscribing/unsubscribing and getting all the current subscribed topics)

2022-07-20 15:58 UTC, tonisevener requested changes
Looks good! Just one small tweak is needed I think after doing some API testing.

2022-07-20 15:58 UTC, tonisevener commented on Wikipedia/Code/TalkPageFetcher.swift
> +                for (topicId, _) in resultSuccess {
I came across a situation with the API where the response was this:

```
{
  "subscriptions": {
    "h-Tsevener-20220720150400": 0,
    "h-TSevener_(WMF)-2022-06-24T18:39:00.000Z": 1
  }
}
```

I had to first make the **unsubscribe** call to `h-Tsevener-20220720150400`, then it started returning with a `0` value in this response. So I think you should check the dictionary value here as well to make sure it's a `1` value, before appending to `subscribedTopics`.

2022-07-26 16:18 UTC, tonisevener requested changes
Working well, just a couple of very minor naming things, thanks!

2022-07-26 16:18 UTC, tonisevener commented on Wikipedia/Code/TalkPageFetcher.swift
> +    func subscribeToTopic(talkPageTitle: String, siteURL: URL, topic: String, shouldSubscribe: Bool, completion: @escaping (Result<Bool, Error>) -> Void) {
Can you add a comment before this method and the next one, explaining that `topic: String` expects the `name` value from `TalkPageItem` `heading` types? I mistakenly tested with the `id` values and I think a comment may help.

2022-07-26 16:18 UTC, tonisevener commented on Wikipedia/Code/TalkPageFetcher.swift
> +    func getAllSubscriptions(siteURL: URL, topics: [String], completion: @escaping (Result<[String], Error>) -> Void) {
Actually now that we know we'll only be sending back the subscribed topics, maybe we should rename this to something like:

```
func getSubscribedTopics(from topics: [String], siteURL: URL, completion: @escaping (Result<[String], Error>) -> Void) {
```

2022-08-01 16:22 UTC, tonisevener approved these changes
Looks good! Can you fix the merge conflicts?

2022-08-01 17:42 UTC, mazevedofs commented
> Looks good! Can you fix the merge conflicts?

Fixed!

2022-08-03 17:43 UTC, merged