Talk pages - iPad tweaks
wikimedia/wikipedia-ios pull request #4364
Opened 2022-10-14 21:22 UTC by tonisevener

**Phabricator:** 
N/A

### Notes
This is a PR to align a few more things to the `readableContentGuide`, so that iPad content lines up with the header. 

I also added a final commit to adjust the full-screen coffee roll so that the scroll indicator appears on the edge. This is more of a personal preference - happy to revert if there's pushback.

### Test Steps
1. Review topic cells, full screen coffee roll and empty state on iPad and iPhone. Confirm there are no layout issues.

### Screenshots/Videos

Before:
![B4bID](https://user-images.githubusercontent.com/3620196/195944792-c5af4781-bce6-4f8b-a834-5f41169d4d40.png)
After:
![HQn7e](https://user-images.githubusercontent.com/3620196/195945294-d71f1860-ba41-4d25-acea-d6312b79610d.png)

Before:
![tRdEm](https://user-images.githubusercontent.com/3620196/195944806-dfc4ff2b-b742-491d-aa11-cc8fa9c2c2ba.png)
After:
![763YE](https://user-images.githubusercontent.com/3620196/195945317-54e46dcf-f967-4fb8-8516-a5a4b6d87f8e.png)

Before:
![ODQKg](https://user-images.githubusercontent.com/3620196/195945171-55be8ea1-09e2-4a24-bc49-daf1e4ad30cf.png)
After:
![aD1GR](https://user-images.githubusercontent.com/3620196/195945391-32801942-4c7c-4658-bbb0-c2ae92b4a841.png)

Before:
![QBP1s](https://user-images.githubusercontent.com/3620196/195945200-61b02416-8053-4484-ad97-e046f1e5d18c.png)
After:
![OnpdE](https://user-images.githubusercontent.com/3620196/195945451-d5608c29-de22-40e2-b58f-96bdbcc70aa4.png)

2022-10-26 20:17 UTC, mazevedofs commented
Looking good, just confirming that this is the intended layout for the button (or should the text have as much padding as the button?)

![IMG_0010](https://user-images.githubusercontent.com/31116510/198127825-b1bfd81c-3d22-40be-8710-93debcdf634f.PNG)

2022-10-26 20:19 UTC, mazevedofs requested changes
Looking good, just confirming that this is the intended layout for the button (or should the text have as much padding as the button?)

![IMG_0010](https://user-images.githubusercontent.com/31116510/198128638-34449be8-c328-4980-ad54-8c6b85190b7c.PNG)

2022-10-26 21:07 UTC, tonisevener commented
> Looking good, just confirming that this is the intended layout for the button (or should the text have as much padding as the button?)
> 
> ![IMG_0010](https://user-images.githubusercontent.com/31116510/198128638-34449be8-c328-4980-ad54-8c6b85190b7c.PNG)

Good catch! I'm not sure on this one. I asked design in the Phab task so we'll see what they say.

2022-10-27 19:59 UTC, mazevedofs approved these changes

2022-10-27 19:59 UTC, merged