Talk page voiceover
wikimedia/wikipedia-ios pull request #4383
Opened 2022-10-31 22:14 UTC by mazevedofs

**Phabricator:** https://phabricator.wikimedia.org/T318611

### Notes
* This PR adds voiceover support to Talk Pages. The goal is to provide better context to some elements on the screen and adjusts the focus when necessary.
* Feel free to suggest text changes that would provide better context to users

### Test Steps
1. With voiceover on, navigate the talk pages, try to post and reply to topics, and simulate errors to check the error feedback.

2022-10-31 22:17 UTC, mazevedofs commented on Wikipedia/Code/TalkPageTopicReplyOnboardingView.swift
> +                    if #available(iOS 14.0, *) { // TODO: remove version check
I didn't add fallback as we're dropping iOS 13 in this version

2022-11-02 16:23 UTC, tonisevener requested changes
Sounding great! I have some thoughts on more items that could be accessible, but I think they make more sense to add them as a follow-on PR. So this is feedback just for the items tackled in this PR.

2022-11-02 23:49 UTC, mazevedofs commented on WMF Framework/CommonStrings.swift
> +    public static let enabledAccessibilityLabel = WMFLocalizedString("talk-page-reply-button-enabled", value: "Enabled", comment: "Accessibility text indicating that the button is enabled")
Good catch, I hadn't noticed this before! Maybe I was moving on between elements too fast. I'll remove those

2022-11-02 23:58 UTC, mazevedofs commented on Wikipedia/Code/TalkPageCell.swift
> +                let replyButtonAccessibilityLabel = CommonStrings.talkPageReplyAccessibilityText
No reason 😂 , I'll move it out of the loop

2022-11-03 00:01 UTC, mazevedofs commented on Wikipedia/Code/TalkPageViewController.swift
> +        if !UIAccessibility.isVoiceOverRunning {
It wasn't reading it out loud, but it worked with breakpoints. That's why I added a way to "delay" it

2022-11-03 00:09 UTC, mazevedofs commented
@tonisevener I guess it's ready for another review!

2022-11-03 21:13 UTC, tonisevener approved these changes
Working great!

2022-11-03 23:13 UTC, merged