Watchlist accessibility improvements
wikimedia/wikipedia-ios pull request #4638
Opened 2023-09-22 20:12 UTC by mazevedofs

**Phabricator:** https://phabricator.wikimedia.org/T342359

### Notes
* This PR adds some accessibility adjustments for voiceOver users to make the watchlist feature easier to navigate
* The main difference is that when VoiceOver is running, tapping on the cell doesn't take you directly to the diff. Instead, it opens the menu with "Go to Diff" as the first action. That was done to make it less confusing to VoiceOver users and to concentrate all actions in one.

### Test Steps
1. With VoiceOver on, access the Watchlist Feature from Article. Add an article to the watchlist, choose the expiration date, and ensure the toast is accessible.
2. Access the watchlist from Account in Settings, make sure it's easy to navigate.
3. Try it on a fresh install so the onboarding modal shows

2023-09-25 22:04 UTC, staykids requested changes
Creative use of the menu button for accessibility here! I think there are several changes we need to make here and conflicts with main to resolve.

2023-09-25 22:04 UTC, staykids commented on Components/Sources/Components/Components/Watchlist/WKWatchlistView.swift
> +            .accessibilityHidden(true)
Should we retain the intrinsic accessibility nature of this view here? Using the modifier means the user gets trapped with no indication about the view itself as it's loading, which could be especially problematic if it's taking a long time.

2023-09-25 22:04 UTC, staykids commented on Components/Sources/Components/Components/Shared/Buttons/WKMenuButtonDelegate.swift
> +    func wkSwiftUIMenuButtonUserDidTapAccessibility(configuration: WKMenuButton.Configuration, item: WKMenuButton.MenuItem?) {}
Same note as elsewhere about finding a way to remove the need for this extra delegate method here and above.

2023-09-26 17:42 UTC, mazevedofs commented on Components/Sources/Components/Components/Watchlist/WKWatchlistView.swift
> +            accessibilityString = "\(project) \(item.timestampStringAccessibility). \(item.title). \(viewModel.localizedStrings.userAccessibility): \(item.username). \(viewModel.localizedStrings.summ
I'm working on this one and will push it soon. All the other minor ones were addressed.

2023-09-26 21:39 UTC, staykids commented on Components/Sources/Components/Components/Watchlist/WKWatchlistViewController.swift
> +        func wkSwiftUIMenuButtonUserDidTapAccessibility(configuration: WKMenuButton.Configuration, item: WKMenuButton.MenuItem?) {
Made Phab task for this: https://phabricator.wikimedia.org/T347433

2023-09-26 21:48 UTC, staykids approved these changes

2023-09-26 21:48 UTC, merged