New fundraising banner and in-app webview donation page
wikimedia/wikipedia-ios pull request #4649
Opened 2023-10-03 17:40 UTC by mazevedofs

**Phabricator:** https://phabricator.wikimedia.org/T333108 & https://phabricator.wikimedia.org/T346823

### Notes
*  This PR updates the UI and actions on our fundraising modal - now the user can choose to be reminded at a later date
* It also keeps the donation flow within the app, opening the pages from an in-app webview
* This PR depends on #4641

### Test Steps
1. Run the experimental app, open it once, background it, and then open it again
2. Set your region to the Netherlands - I was hard-coding "NL" on all methods that verify the country code
3. Add Dutch to your languages
4. Test closing using the "X" button or the "already donated" button (the last one) - it should not show the modal again
5. Delete the app, reinstall, repeat step 1
6. Select maybe later. Check if the reminder toast shows.
7. Visit the article again. it should not show the modal. 
8. Change the date on your phone to tomorrow. Visit the article, it should show the modal.
9. Reinstall and uninstall, repeat step 1. This time, donate.
10. Verify that the `back to article` button shows on the bottom of the Thank you page.
11. Close the web view and verify that the thank you toast shows

2023-10-03 18:19 UTC, mazevedofs commented on Wikipedia/Code/SinglePageWebViewController.swift
> +    }
This feels a little hacky, so I'm open to suggestions here :D

2023-10-04 03:14 UTC, tonisevener requested changes
Thanks! Looking great. This first round is a code-only review, I'll test it tomorrow and will let you know if I find anything else. Mainly just small naming tweaks and moving bits of code around.

2023-10-05 18:07 UTC, mazevedofs commented on Wikipedia/Code/SinglePageWebViewController.swift
> +        button.setTitle(CommonStrings.returnToArticle, for: .normal)
I'll leave a TODO on this one for now, and I can do a fix PR after yours is up

2023-10-05 18:37 UTC, tonisevener commented on Wikipedia/Code/ArticleViewController+Announcements.swift
> +            }
@mazevedofs Let me know if you have trouble displaying this alert view. There are quite a few hoops to jump through to get to a state where the app thinks a user qualifies for this prompt. Going through the Test steps "Prep work:" and then the "testing locally" steps 1-3 on the https://github.com/wikimedia/wikipedia-ios/pull/4641 description should get things set up for displaying this prompt.

2023-10-05 23:26 UTC, tonisevener commented on Wikipedia/Code/ArticleViewController+Announcements.swift
> +            }
@mazevedofs FYI, I noticed a bug with this presentation logic on my code. I pushed a fix just now, hope that's okay!

2023-10-09 16:15 UTC, tonisevener approved these changes

2023-10-09 16:35 UTC, merged