Native Page Editor Container and UI Tests
wikimedia/wikipedia-ios pull request #4682
Opened 2023-11-21 20:38 UTC by mazevedofs

**Phabricator:** https://phabricator.wikimedia.org/T347870

### Notes
* This PR brings over to the main app the contents of this PR https://github.com/wikimedia/wikipedia-ios-components/pull/9
* It also adjusts UI Tests to run in isolation from unit tests

### Test Steps
1. To test the component itself, run the app On the staging target and tap edit on an article. You should see the new editor
2. To run the UI Tests, hit CMD +U on the new WikipediaUITests target
3. Run the tests on  Xcode Cloud - manually trigger the UI Tests workflow under the main app configurations

Note: currently the theming is not working on the test plan configurations, I'm investigating that

2023-11-29 23:04 UTC, tonisevener requested changes
Nice work, it's looking good! I noticed the theming in the UI tests weren't working quite right on my machine, so I pushed a fix for that. I also reverted any UITest mentions in the other schemes that seemed unnecessary to me. Let me know if that works for you.

Unit tests are failing because of merge conflicts with `main`, but hopefully they'll run again once conflicts are fixed.

2023-11-29 23:04 UTC, tonisevener commented on Wikipedia.xcodeproj/xcshareddata/xcschemes/NotificationServiceExtension.xcscheme
> +      notificationPayloadFile = "PushNotificationPayload.apns">
Xcode automatically changed this on me, FYI.

2023-12-04 20:41 UTC, mazevedofs commented on WMF Framework/CommonStrings.swift
> +    public static let accessibilityLabelButtonSubscript = WMFLocalizedString("source-editor-accessibility-label-subscript", value: "Add subscript formatting", comment: "Accessibility label for the su
I prefer to check in with design on this one.

2023-12-04 20:46 UTC, mazevedofs commented
> Nice work, it's looking good! I noticed the theming in the UI tests weren't working quite right on my machine, so I pushed a fix for that. I also reverted any UITest mentions in the other schemes that seemed unnecessary to me. Let me know if that works for you.
> 
> Unit tests are failing because of merge conflicts with `main`, but hopefully they'll run again once conflicts are fixed.

Thanks for fixing the theming, it wasn't really working, but I couldn't figure it out (and forgot to ask about it on our 1:1s)

2023-12-05 14:19 UTC, tonisevener approved these changes
👏 Working great!

2023-12-05 14:20 UTC, tonisevener commented on Wikipedia/Code/ExploreViewController.swift
> +        // protocol conformance to run UI Tests
Sorry, I missed that this was needed. 😅

2023-12-05 16:09 UTC, merged