T356255 - Picture Of The day bug fixes
wikimedia/wikipedia-ios pull request #4836
Opened 2024-05-02 10:40 UTC by spatel

**Phabricator:** 
https://phabricator.wikimedia.org/T356255

---

### Test Steps

1. Fresh install of the app (primary language English)
2. Background the app > add POTD widget to home screen
3. Tap the widget (it deeplinks to the POTD gallery view) ✅
4. Settings > My Languages > Add language (e.g. Spanish)
5. Change the primary language (e.g. to Spanish)
6. Close settings > refresh the Explore tab (pull-to-refresh)
7. Background the app > tap POTD widget
8. The app launches but the deeplink does nothing (it actually only works against the original primary language i.e. English) ❌

**Expected behaviour**: the app should launch and open the POTD image gallery view

---

### Notes

I split this into 2 commits (one of which is just clang-format changes), so you only really need to review [this commit](https://github.com/wikimedia/wikipedia-ios/commit/200efbf9f1bc6af7fb56ffcdae3d4e1ecf8d8824)

#### Possible root cause

I think this could be due to the fact the POTD image only gets saved once in the data store against the app's initial site URL (i.e. initial primary language). After that, the same record gets continually modified. This is deliberate (to avoid duplicate images from appearing across each language feed) and there was a comment in the code to explain why this was originally done. However, I think you may be running into issues with content URL deep-links from widgets etc because they appear to be querying data against site URL (even for POTD).

#### Worked example

(N.B. This is based on the test steps mentioned above)

1. The "English" feed is initially loaded and it inserts a new POTD content record in the data store (against the "EN" site URL)
2. The user later switches primary language to "Spanish" and launches the app from a deeplink like this: `wikipedia://content/picture-of-the-day/wikipedia.org/es/2024/05/01`
3. The app tries processes the deeplink (and reaches [`[WMFAppViewController processUserActivity:animated:completion]`](https://github.com/wikimedia/wikipedia-ios/blob/6182dd8cc2717655dceaed4b5650f5afae5e2124/Wikipedia/Code/WMFAppViewController.m#L1185))
4. It [queries the data store for a POTD (_against the **ES** site URL_)](https://github.com/wikimedia/wikipedia-ios/blob/6182dd8cc2717655dceaed4b5650f5afae5e2124/Wikipedia/Code/WMFAppViewController.m#L1191) but finds no match (because it was originally stored against "EN")
5. It then [falls through to here](https://github.com/wikimedia/wikipedia-ios/blob/6182dd8cc2717655dceaed4b5650f5afae5e2124/Wikipedia/Code/WMFAppViewController.m#L1206) where it eventually tries to [refresh all the feeds and save the POTD again](https://github.com/wikimedia/wikipedia-ios/blob/6182dd8cc2717655dceaed4b5650f5afae5e2124/Wikipedia/Code/WMFFeedContentSource.m#L233)
6. At this point it **DOESN'T** query against the site URL, so it finds the existing "EN" record and updates it.
7. Once everything is refreshed, the app once again queries for the POTD (i.e. now expecting the **ES** record to exist) - but since it doesn't exist, nothing happens

---

### Screenshots/Videos

Demo of the Explore feed's POTD image description (at the bottom of the image) flipping between primary & secondary language:

https://github.com/wikimedia/wikipedia-ios/assets/478681/5dc97b15-637a-4109-acb2-1eb12270e500

2024-05-02 10:47 UTC, spatel commented on Wikipedia/Code/WMFFeedContentSource.m
> +        }
This is the main logic change (1 of 2). 

Here's what I've done:

- The original logic is still the same (it's just moved inside the `if (isPrimaryLanguageFeed) { }` statement)
- The `else` part is new and prevents duplicates by removing any POTD records found against non-primary languages.
- The logging statements are new and were really just to help me troubleshoot (please let me know if you'd like me to remove them).

2024-05-02 10:50 UTC, spatel commented on Wikipedia/Code/WMFFeedContentSource.m
> +    return (id)[moc groupOfKind:WMFContentGroupKindPictureOfTheDay forDate:date siteURL:self.siteURL];
This is the other main logic change (part 2 of 2). We use the site URL (in the same way as other content) and the duplicate logic is now handled as part of the `save` method.

_N.B. All other changes to this file are just clang-format changes_

2024-05-23 23:04 UTC, tonisevener requested changes
@spatel Sorry for the delay on this review. Excellent investigative work, as always. 🙂

I found a couple of bugs, but overall I'm good with your approach in this method. Let us know if these fixes give you trouble and we can discuss alternatives. Thanks!

2024-05-24 17:33 UTC, spatel commented on Wikipedia/Code/WMFFeedContentSource.m
> +}
**Change 2 of 3**

This now inserts (or updates) POTD against the primary language only (and removes any duplicate ones found against secondary languages).

2024-05-24 18:55 UTC, merged