T370367: [ALT TEXT] Add overflow menu and actions for alt text
wikimedia/wikipedia-ios pull request #4936
Opened 2024-08-22 17:03 UTC by l-olson1214

**Phabricator:** 
https://phabricator.wikimedia.org/T370367
### Notes
* 

### Test Steps
1. 

### Screenshots/Videos

2024-08-22 18:23 UTC, mazevedofs commented
Hi @l-olson1214 👋 
Great start! Nice to see you diving into our codebase 

I made some minor comments and found one issue that we can work on together if you'd like:
- After clicking "Learn more" to the in-app web view, the half-sheet modal is not presented with the alt text task when returning to the feature. That is a recurring challenge with that kind of component, so some work is expected to be done around it. 

In the PR description section, when it's ready for final review, you can add more detail about your changes, any comments or considerations (or even questions for the reviewer)
We also add test steps on test notes. 
Screenshots are not required. You can add them if it's a new UI or if it can be helpful for the reviewer.

2024-08-22 18:42 UTC, mazevedofs requested changes

2024-08-22 18:42 UTC, mazevedofs commented on Wikipedia/Code/ArticleViewController.swift
> +                image: UIImage(systemName: "ellipsis.circle"),
We still have several image literals all over the code, but we're trying to move on to using our WMFSFSymbolIcon component for consistency.

So this bit could be:

`UIBarButtonItem(image: WMFSFSymbolIcon.for(symbol: .ellipsisBubble)`

2024-08-22 18:42 UTC, mazevedofs commented on Wikipedia/Code/ArticleViewController.swift
> +            rightBarButtonItem.tintColor = .link
Our theming is a little weird (we can talk more about it!), so we get colors from the theme like this:

`theme.colors.link`

This class already references the Theme class that propagates theme changes across the app.

2024-08-22 18:42 UTC, mazevedofs commented on Wikipedia/Code/ArticleViewController.swift
> +            let emailBodyLine5 = WMFLocalizedString("image-recommendations-email-fifth-line", value: "[Screenshots or Links]", comment: "Text for Image recommendations pre-filled issue report email.
For the strings here from line 1097 forward:

If the copy is the same, you can move it into CommonStrings, as we talked about during eng sync. You can keep the keys the same so they don't need to be translated again (changing keys will kick off that whole process as it was a new string).

2024-08-22 18:42 UTC, mazevedofs commented on Wikipedia/Code/ArticleViewController.swift
> +        let reportIssues = UIAction(title: CommonStrings.problemWithFeatureTitle, image: UIImage(systemName: "flag"), handler: { [weak self] _ in
Same for the images here - they could be WMFSFSymbolIcon. You can add a new SFSymbol if we don't have it already

2024-08-23 15:00 UTC, mazevedofs requested changes
Looking great! The send email func is working. I made a comment about adding the translations, let me know if you need help with that

2024-08-23 15:31 UTC, l-olson1214 commented on Wikipedia/Code/ArticleViewController.swift
> +
Added! 
Out of curiosity, when translating Chinese (or different characters in general), what tool do you use to get them to unicode?

2024-08-23 16:54 UTC, mazevedofs commented on Wikipedia/Code/ArticleViewController.swift
> +
These files don't need Unicode characters, so you can copy and paste them directly. Did you push these changes? I can't see them on github's interface

2024-08-23 17:32 UTC, mazevedofs approved these changes
Looks great!

2024-08-23 18:54 UTC, merged