Explore Feed: add icons to peek controller context menu
wikimedia/wikipedia-ios pull request #4949
Opened 2024-08-29 05:09 UTC by evieluvsrainbows

**Phabricator:** N/A

### Notes
* Adds icons in the context menu for the peek experience in the Explore Feed
* This uses SF Symbols, the built-in icons library. I tried to use the most appropriate icons for each action.

### Test Steps
1. Run the app, hold down on an article in Explore Feed
2. Look at the new icons! :smiley:

### Screenshots/Videos

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-28 at 23 06 20](https://github.com/user-attachments/assets/d2cc5a0b-8af4-4ca4-a849-48a05a248e54)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-28 at 23 07 46](https://github.com/user-attachments/assets/4e030c27-66d7-4538-82cc-9be7a97530e4)

2024-09-06 20:54 UTC, tonisevener commented
Hi @evelynharthbrooke, thank you for the improvement! I have created an associated Phabricator task so that our designer can take a look - https://phabricator.wikimedia.org/T374282. I am putting these changes through design review before we merge and will update this PR if any tweaks are needed.

2024-09-09 15:02 UTC, tonisevener requested changes
Thanks for the PR @evelynharthbrooke! This has been approved by design. I have one minor request from code review. Let us know if you have any questions!

2024-09-10 04:36 UTC, evelynharthbrooke commented
> Thanks for the PR @evelynharthbrooke! This has been approved by design. I have one minor request from code review. Let us know if you have any questions!

I will get that done as soon as possible once i have a bit of free time! :)

2024-09-10 23:03 UTC, evelynharthbrooke commented
I will update this PR with the recommended changes as soon as the PR that adds support for Xcode 16 is merged, as my Mac is on Sequoia and Xcode 16 now, and I don't want to push a whole bunch of irrelevant changes to my branches.

2024-09-11 00:37 UTC, evelynharthbrooke commented on Wikipedia/Code/ArticleViewController+LinkPreviewing.swift
> +        let readAction = UIAction(title: readActionTitle, image: UIImage(systemName: "book"), handler: { (action) in
Done!

2024-09-11 00:38 UTC, evelynharthbrooke commented
@tonisevener I have made the requested changes. :)

2024-09-11 16:18 UTC, tonisevener approved these changes

2024-09-11 16:35 UTC, tonisevener commented
Looks great, thank you @evelynharthbrooke!

2024-09-11 16:35 UTC, merged