UI touchups YIR
wikimedia/wikipedia-ios pull request #5020
Opened 2024-10-15 20:04 UTC by l-olson1214

**Phabricator:** 
https://phabricator.wikimedia.org/T376071
https://phabricator.wikimedia.org/T375566

### Notes
* Bundled both tickets
* Moved out some logic from slideshow
* Created first slide file (very similar to onboarding)

### Test Steps
1. Put in It/Fr, location in It/Fr
2. Navigate to YiR
3. Ensure navigation dots work, have correct colors, are horizontally aligned, animation is correct, and scrollview is correct

### Screenshots/Videos

https://github.com/user-attachments/assets/eb9914a8-560c-4812-ba18-0ca176a37119

2024-10-15 22:12 UTC, tonisevener requested changes

2024-10-15 22:12 UTC, tonisevener commented on WMFComponents/Sources/WMFComponents/Components/Year in Review/WMFYearInReviewScrollView.swift
> +                .padding(EdgeInsets(top: 0, leading: sizeClassPadding, bottom: scrollViewBottomInset, trailing: sizeClassPadding))
@l-olson1214 I'm not sure why `WMFOnboardingView` used this large `scrollViewBottomInset`, but with your slides I think passing in `bottom: 0` here is working better. If you use the additional padding, your bottom toolbar thinks that some content is already displayed off screen, so a slight shadow appears at the bottom on some slides:

![screenshot](https://github.com/user-attachments/assets/2cbf9cfa-ba0c-4011-8b88-f6df6acf5b9a)

2024-10-15 22:24 UTC, tonisevener commented on WMFComponents/Sources/WMFComponents/Components/Year in Review/WMFYearInReviewScrollView.swift
> +                .padding(EdgeInsets(top: 0, leading: sizeClassPadding, bottom: scrollViewBottomInset, trailing: sizeClassPadding))
Update: Actually I just noticed that you might need the larger content inset for the intro slide, which has buttons potentially covering up the scroll view content. So something to think about - if design review kicks this back due to the shadow, you may be able to fix it by making that `scrollViewBottomInset` property configurable from the outside and setting it to 0 for the slides with a bottom toolbar.

2024-10-16 13:18 UTC, l-olson1214 commented on WMFComponents/Sources/WMFComponents/Components/Year in Review/WMFYearInReview.swift
> +                        UIPageControl.appearance().isHidden = true
Ah dang - I was trying to keep the swipe gesture that comes with it for free - do you think I should go in and manually add it?

2024-10-17 21:17 UTC, tonisevener approved these changes

2024-10-17 22:35 UTC, merged