[YiR] Update flow to show collective for logged out users
wikimedia/wikipedia-ios pull request #5085
Opened 2024-11-20 18:52 UTC by tonisevener

**Phabricator:** https://phabricator.wikimedia.org/T379796

### Notes
This PR removes the requirement that a user must be eligible to see at least one personalized slide for the entry point to appear. It also defaults to all collective slides from the coordinator if the user is logged out.

### Test Steps
1. Ensure device/simulator is in target region. Fresh install app. Log out of app if needed. Go to app Settings and turn off Year in Review. Build up an article history. Now go to app settings and turn ON year in review.
2. Year in Review entry point should show in Profile.
3. You should only see collective slides.
4. Complete year in review flow, answer survey, then log into an account with edits after login prompt.
5. After logging in, go back to year in review flow from Profile.
6. You should see personalized slides now.
7. Go back to profile, log out.
8. After logging out, go back to year in review flow from Profile.
9. You should only see collective slides now.

2024-11-25 20:16 UTC, l-olson1214 requested changes
I'm seeing the first two slides as being personalized on log out, but that may have also included some of the merge conflicts - let's meet up when you're back from PTO!

2024-12-03 15:13 UTC, tonisevener commented
@l-olson1214 I fixed some merge conflicts in this PR, let me know if it's still acting weird for you!

2024-12-05 23:11 UTC, tonisevener commented
@l-olson1214 This is ready for another review! I updated the test steps - the old ones were outdated.

2024-12-09 16:25 UTC, l-olson1214 approved these changes

2024-12-09 16:39 UTC, merged